---
title: "『行動データの計算論モデリング』サポートページ"
---

## はじめに

本WEBサイトは『行動データの計算論モデリング』 (2018年秋に出版予定) のサポートページです。現在作成中です。

## ソースコード

R, Stan等のソースコード等のファイルは以下のGitHubリポジトリに設置しています (作成中):

[https://github.com/kkatahira/cmbd-book](https://github.com/kkatahira/cmbd-book)

ソースコードをまとめたzipファイルは[こちら](./codes/qlearning_simulation.zip)からもダウンロードできます (作成中)。


## ソースコードについて

RコードはRStudio上で動かすことを想定しています。

必要なパッケージは章ごとに記します。
インストールして使用してください。
例えば'tidyverse'を使用する必要があるときは，

> install.packages('tidyverse')

とコマンドライン上で打てばインストールすることができます。

ソースコードは章ごとにフォルダが分けられています。

### 第2章

第2章では，できるだけどのコードも単体で動くようにしました。
本来はシミュレーションによるデータの生成と，パラメータ推定，結果の描画はコードを分けた方が，共通した処理はルーティン化できてよいと思うのですが，初学者にとっては一つのコードで一連の処理をしてグラフまで出る，という方がとっつきやすいと考えたからです。

- RW_simulation.R	
-- RWモデルのシミュレーションをします。図2.2を作成します。

- plot_softmax.R	
-- ソフトマックス関数をプロットします。図2.4を作成します。

- qlearning_simulation.R
-- Q学習モデルのシミュレーションにより選択データを生成し，そのデータに対し最尤推定によりQ学習モデルのパラメータ推定をします。図2.5を作成します。

- qlearning_plot_ll_function.R	
-- 図2.5と同じデータを生成し，それに対するQ学習モデルの対数尤度関数をプロットします (コードの前半はqlearning_simulation.Rと同じです)。図2.6を作成します。

- qlearning_model_comparison.R	
-- 図2.5と同じデータを生成し，それに対するQ学習モデル，WSLSモデル，ランダムモデルの最尤推定を行い，モデル間を比較します。図2.7を作成します。

<!--
```{r}
# メモリとグラフのクリア
rm(list=ls())
graphics.off()

# 描画用ライブラリの読み込み
library(tidyverse)

#----------------------------------------------------------#
# RW modelのシミュレーションの実行
#----------------------------------------------------------#

# 乱数のシードの設定 
set.seed(928)

# 試行数
T <- 50

# 学習率
alpha <- 0.2

# 報酬確率
pr <- 0.8

# 連合強度( 価値) V と報酬r の配列を作成
V <- numeric(T)
r <- numeric(T)

for (t in 1:T) {
  
  # 報酬の有無の決定
  r[t] <- as.numeric( runif(1 ,0 ,1) < pr)
  
  # 連合強度の更新
  if (t < T) {
    V[t +1] <- V[t] + alpha * (r[t] - V[t])
  }
}

#----------------------------------------------------------#
# グラフの描画
#----------------------------------------------------------#

# ggplotのテーマ設定
ggplot() + theme_set(theme_bw(base_size = 18)) 

# ウィンドウの生成
x11()

# 描画するデータをデータフレームにまとめる
dfplot <- data.frame(trials = 1:T, 
                 V = V,
                 r = as.factor(r))

# 描画
g <- ggplot(dfplot, aes(x = trials, y = V)) +
  geom_line(aes(y = V), linetype = 1, size=1.2) +
  geom_point(data = dfplot %>% filter(r == 1), 
             aes(x = trials, y = 1.12), shape = 25, size = 1.5) + 
  scale_y_continuous(breaks=c(0, 0.5, 1.0), labels = c(0,0.5,1)) +
  xlab("試行") +
  ylab("連合強度 V") 

print(g)
```
-->
